apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: us-tails 
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/http-endpoint: "enabled"
    tailscale.com/tags: "tag:us"
spec:
  tls:
  - hosts:
    - us-tails
  rules:
  - http:
      paths:
      - backend:
          service:
            name: tails
            port:
              number: 80
        pathType: Prefix 
        path: /
  ingressClassName: tailscale
