apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ingress-proxies
spec:
  type: ingress
  replicas: 2
  tags: ["tag:euingress"]
  proxyClass: le-staging
---
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: le-staging
spec:
 useLetsEncryptStagingEnvironment: true
